# Generated by Django 3.0.6 on 2020-06-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200618_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-user'], 'verbose_name': 'коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
